#!/usr/bin/env bash

echo "Install local . . ."

export npm_config_cache=/tmp/npm/cache
npm i
rm -rf /tmp/npm/cache


if [ ! -d /.composer ]; then
    mkdir /.composer
fi
chmod -R ugo+rw /.composer

composer install


